config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/index'

  get 'pages/info'

root :to => redirect('/pages/index')
  get    '/weddingguests'           => 'weddingguests#index'

  get    '/weddingguests/new'       => 'weddingguests#new', as: 'new_weddingguest'
  get    '/weddingguests/:id/edit'  => 'weddingguests#edit', as: 'edit_weddingguest'
  get    '/weddingguests/:id'       => 'weddingguests#show', as: 'weddingguest'

  post   '/weddingguests'           => 'weddingguests#create'
  patch  '/weddingguests/:id'       => 'weddingguests#update'
  put    '/weddingguests/:id'       => 'weddingguests#update'

  delete '/weddingguests/:id'       => 'weddingguests#destroy'

end

app/models/weddingguest.rb
class Weddingguest < ActiveRecord::Base
mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def info
  end
end

app/controllers/weddingguests_controller.rb
class WeddingguestsController < ApplicationController
  def index
    @weddingguests = Weddingguest.all
    render 'index'
  end
  def show
    @weddingguest = Weddingguest.find(params[:id])
    render 'show'
  end
  def new
    @weddingguest = Weddingguest.new
    render 'new'
  end
  def edit
    @weddingguest = Weddingguest.find(params[:id])
    render 'edit'
  end
  def create
    @weddingguest = Weddingguest.new(weddingguest_params)
    if @weddingguest.save
      redirect_to @weddingguest, notice: 'Weddingguest was successfully created.'
    else
      render action: 'new'
    end
  end
  def update
    @weddingguest = Weddingguest.find(params[:id])
    if @weddingguest.update(weddingguest_params)
      redirect_to @weddingguest, notice: 'Weddingguest was successfully updated.'
    else
      render action: 'edit'
    end
  end
  def destroy
    @weddingguest = Weddingguest.find(params[:id])
    @weddingguest.destroy
    redirect_to weddingguests_url, notice: 'Weddingguest was successfully destroyed.'
  end
  private
  # Only allow a trusted parameter "white list" through.
  def weddingguest_params
    params.require(:weddingguest).permit(:name, :description, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsgirls</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class='navbar navbar-default navbar-fixed-top' role='navigation'>
  <div class='container'>
    <div class='navbar-header'>
      <a class='navbar-brand' href='/'>The weddingguest app</a>
    </div>
    <ul class='nav navbar-nav'>
      <li>
        <a href='/weddingguests'>Wedding guests</a>
      </li>
      <li>
        <a href='/pages/info'>Info</a>
      </li>
    </ul>
  </div>
</nav>

<div class='container'>
  <%= yield %>
</div>
<footer>
  <div class='container'>
   Wedding guests Axel & Michelle - 2 September 2017
  </div>
</footer>
</body>
</html>

app/views/pages/index.html.erb
<div class="Index"><h1>Welcome to our wedding guestlist!</h1>
<div>You are among the lucky few that are invited to our awesome wedding in Prague!</div>
<div>Find out who else was as lucky as you by browsing our wedding guest app.</div>
<div>To break the ice during the wedding day, and make mingling fun, you can also find interesting information about the other guests, such as funfacts!</div>
<div>Great conversation starters if we do say so ourselves!</div></div>

app/views/pages/info.html.erb
<div class="Infopage"><h1>Wedding Axel & Michelle</h1>
<div>We're getting married on the 2nd of September 2017 and invited you and our other dearest friends and family to celebrate with us.</div> 
<div>On this website you find a face list and a 'who's who' of all the wedding guests.</div>
<img class="Info" src="https://scontent-arn2-1.xx.fbcdn.net/v/t1.0-9/10402745_10202259908843145_304640962877297290_n.jpg?oh=fd5fd99c32a6406fb7b1b41da11d356b&oe=59AF5BD7"></div>

app/views/weddingguests/_form.html.erb
<%= form_for(@weddingguest) do |f| %>
  <% if @weddingguest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weddingguest.errors.count, "error") %> prohibited this weddingguest from being saved:</h2>

      <ul>
      <% @weddingguest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weddingguests/edit.html.erb
<h1>Editing Weddingguest</h1>

<%= render 'form' %>

<%= link_to 'Show', @weddingguest %> |
<%= link_to 'Back', weddingguests_path %>

app/views/weddingguests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wedding guests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weddingguests.each do |weddingguest| %>
      <tr>
        <td><%= link_to weddingguest.name, weddingguest %></td>
        <td><%= weddingguest.description %></td>
        <td><%= image_tag(weddingguest.picture_url) if weddingguest.picture.present? %></td>
        <td><%= link_to 'Edit', edit_weddingguest_path(weddingguest) %></td>
        <td><%= link_to 'Destroy', weddingguest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weddingguest', new_weddingguest_path %>

app/views/weddingguests/new.html.erb
<h1>New Weddingguest</h1>

<%= render 'form' %>

<%= link_to 'Back', weddingguests_path %>

app/views/weddingguests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @weddingguest.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @weddingguest.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@weddingguest.picture_url) if @weddingguest.picture.present? %>
</p>

<%= link_to 'Edit', edit_weddingguest_path(@weddingguest) %> |
<%= link_to 'Back', weddingguests_path %>